services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: task-db
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Backend Service
  backend:
    build: ./Project_Tasks_Management
    container_name: task-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Note the 'mysql' in the URL and the correct driver
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/taskdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # Frontend Service (Stays the same)
  frontend:
    build: ./project-management-frontend
    container_name: task-ui
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:  # <--- Changed name from postgres_data